/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BqYXyOlM51V
 */
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import EchartsDashboard from "@/components/ui/Dashboard"
import {NavBar} from "./header"
import React, { useEffect, useState } from 'react';
import {analyzeSimilarity} from"@/app/api/api"
export function TextSimiler() {
  const [text1, setText1] = useState('');
  const [text2, setText2] = useState('');
  const [similarityResult, setSimilarityResult] = useState(0);
  const [cosine_sim, setCosine_sim] = useState(0);
  const [correlation_sim, setCorrelation_sim] = useState(0);
  const [textVector,setTextVector]=useState(1)
  const handleAnalyze = async () => {
    try {
      console.log("Textvector",textVector)
      const result = await analyzeSimilarity(textVector,text1, text2);
      setCosine_sim(Number(result.cosine_sim*100).toFixed(4))
      setCorrelation_sim(Number(result.correlation_sim*100).toFixed(4))
      const roundedResult = Number((result.cosine_sim*100+result.correlation_sim*100)/2).toFixed(2);
      setSimilarityResult(roundedResult);
    } catch (error) {
      // 在这里处理请求失败的情况
      console.error('分析失败：', error);
    }
  };
    // useEffect(()=>{
    //   const fetchTextVector= async() =>{
    //       console.log("setTextVector: "+textVector)
    //   }
    //   fetchTextVector()
    // },[textVector])
  return (
    (<div
      key="1"
      className="flex flex-col min-h-screen p-4 md:p-8 bg-gradient-to-r from-[#f3f4f6] to-[#a1c9f1] text-[#2d3748] font-sans">
     <NavBar />
     <div className="flex flex-col">
        <select onChange={(e) => setTextVector(e.target.value)} className="mb-6 font-bold bg-gradient-to-r from-[#f3f4f6] to-[#a1c9f1] w-32 h-8" >
          <option className="mb-4 w-2 "  value={1}>平均向量(适合句子)</option>
          <option className="mb-4  "  value={2}>TF-IDF向量(适合文章)</option>
        </select>
    </div>
      <div className="flex flex-col md:grid md:grid-cols-2 gap-4 flex-grow">
        <Card
          className="p-4 rounded-lg shadow-lg bg-gradient-to-r from-[#edf2f7] to-[#a1c9f1] border border-gray-200 border-[#2d3748] dark:border-gray-800">
          <CardHeader className="mb-4">
            <h2
              className="text-2xl font-bold text-[#2d3748] border-b-2 border-[#2d3748] inline-block pb-1">文本1</h2>
          </CardHeader>
          <CardContent>
            <textarea
              aria-label="Input Text 1"
              className="border rounded-lg w-full h-32 p-2 bg-[#f7fafc] text-[#2d3748] font-sans border-[#2d3748] shadow-md"
              id="text1"
              value={text1}
              onChange={(e) => setText1(e.target.value)}
              placeholder="请输入文本" />
          </CardContent>
        </Card>
        <Card
          className="p-4 rounded-lg shadow-lg bg-gradient-to-r from-[#edf2f7] to-[#a1c9f1] border border-gray-200 border-[#2d3748] dark:border-gray-800">
          <CardHeader className="mb-4">
            <h2
              className="text-2xl font-bold text-[#2d3748] border-b-2 border-[#2d3748] inline-block pb-1">文本2</h2>
          </CardHeader>
          <CardContent>
            <textarea
              aria-label="Input Text 2"
              className="border rounded-lg w-full h-32 p-2 bg-[#f7fafc] text-[#2d3748] font-sans border-[#2d3748] shadow-md"
              id="text2"
              value={text2}
              onChange={(e) => setText2(e.target.value)}
              placeholder="请输入文本" />
          </CardContent>
        </Card>
      </div>
      <Button
        aria-label="Analyze Button"
        onClick={handleAnalyze}
        className="w-full h-12 my-6 bg-gradient-to-r from-[#2d3748] to-[#4a5568] text-[#f3f4f6] rounded-lg shadow-md border-2 border-[#4a5568] hover:from-[#2d3748] hover:to-[#4a5568] active:scale-95">
        <MicroscopeIcon className="w-4 h-4 mr-2 inline-block" />
        立即分析
      </Button>
      <Card
        className="p-4 rounded-lg shadow-lg bg-gradient-to-r from-[#edf2f7] to-[#a1c9f1] border border-gray-200 border-[#2d3748] dark:border-gray-800">
        <CardHeader className="mb-4">
          <h2
            className="text-2xl font-bold text-[#2d3748] border-b-2 border-[#2d3748] inline-block pb-1">分析结果</h2>
        </CardHeader>
        <CardContent>
          <div className="grid gap-2 py-6">
            <CardHeader className="flex w-full items-center py-2 text-lg font-semibold">
                余弦相似度：{cosine_sim}
            </CardHeader>
            <CardHeader className="flex w-full items-center py-2 text-lg font-semibold">
                相关系数相似度：{correlation_sim}
            </CardHeader>
          </div>
        </CardContent>
        <Card   className="p-4 rounded-lg shadow-lg bg-gradient-to-r from-[#edf2f7] to-[#a1c9f1] border border-gray-200 border-[#2d3748] dark:border-gray-800">
        <CardHeader className="flex w-full items-left py-2 text-lg font-semibold">
                综合相似度：
            </CardHeader>
            <CardContent>
            <EchartsDashboard value={similarityResult}/>
            </CardContent>
            </Card>
      </Card>
    </div>)
  );
}



function MicroscopeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}